# Generated by Django 5.1.4 on 2025-02-25 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(default=0)),
                ('chest', models.FloatField(default=0)),
                ('abdomen', models.FloatField(default=0)),
                ('back', models.FloatField(default=0)),
                ('arm_left', models.FloatField(default=0)),
                ('arm_right', models.FloatField(default=0)),
                ('leg_left', models.FloatField(default=0)),
                ('leg_right', models.FloatField(default=0)),
                ('waist', models.FloatField(default=0)),
                ('hips', models.FloatField(default=0)),
                ('photo_back', models.CharField(max_length=140, null=True)),
                ('photo_front', models.CharField(max_length=140, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
