# Generated by Django 5.1.4 on 2025-02-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='arm',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='leg',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='photo',
        ),
        migrations.AddField(
            model_name='measure',
            name='abdomen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measure',
            name='arm_left',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measure',
            name='arm_right',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measure',
            name='hips',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measure',
            name='leg_left',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measure',
            name='leg_right',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measure',
            name='photo_back',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='photo_front',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='measure',
            name='back',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='measure',
            name='chest',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='measure',
            name='waist',
            field=models.FloatField(default=0),
        ),
    ]
