# Generated by Django 5.1.4 on 2025-02-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='forearm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measure',
            name='glutes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measure',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measure',
            name='photo_left',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='measures/'),
        ),
        migrations.AddField(
            model_name='measure',
            name='photo_right',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='measures/'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='photo_back',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='measures/'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='photo_front',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='measures/'),
        ),
    ]
