# Generated by Django 5.1.4 on 2025-03-19 18:01

import measures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measures',
            field=models.JSONField(blank=True, default=measures.models.default_muscles, null=True),
        ),
    ]
