# Generated by Django 5.1.4 on 2025-04-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0002_alter_measure_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure',
            options={},
        ),
    ]
