# Generated by Django 5.1.4 on 2025-03-05 09:17

import measures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0002_measure_forearm_measure_glutes_measure_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='photo_back',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=measures.models.measure_directory_path),
        ),
        migrations.AlterField(
            model_name='measure',
            name='photo_front',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=measures.models.measure_directory_path),
        ),
        migrations.AlterField(
            model_name='measure',
            name='photo_left',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=measures.models.measure_directory_path),
        ),
        migrations.AlterField(
            model_name='measure',
            name='photo_right',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=measures.models.measure_directory_path),
        ),
    ]
