# Generated by Django 5.1.4 on 2025-02-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0002_remove_measure_arm_remove_measure_leg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='name',
        ),
    ]
