# Generated by Django 5.1.4 on 2025-02-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='user',
        ),
    ]
