# Generated by Django 5.1.4 on 2025-05-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={},
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='routineexcercise',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
