services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000
    volumes:
      - static_files:/app/staticfiles
    env_file:
      - .env
    networks:
      - django_docker_net
  nginx:
    image: nginx:1.25
    ports:
      - "3000:80"
    volumes:
      - ./nginx/custom-nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/app/staticfiles
    depends_on:
      - server
    networks:
      - django_docker_net

networks:
  django_docker_net:
    driver: bridge

volumes:
    db-data:
    static_files:

