# Generated by Django 5.1.4 on 2025-06-05 05:05

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.custom_upload_to),
        ),
    ]
