# Generated by Django 5.1.4 on 2025-04-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={},
        ),
    ]
