# Generated by Django 5.1.4 on 2025-05-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_alter_catalog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='key',
            field=models.CharField(choices=[('muscle', 'Musculo'), ('equipment', 'Equipo')], max_length=140),
        ),
    ]
