# Generated by Django 5.1.4 on 2025-05-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalog_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogs/'),
        ),
    ]
