# Generated by Django 5.1.4 on 2025-05-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_commentreplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreplies',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='comments.comment'),
        ),
    ]
