# Generated by Django 5.1.4 on 2025-06-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
    ]
