# Generated by Django 5.1.4 on 2025-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jwttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
