# Generated by Django 5.1.4 on 2025-03-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='gallery/'),
        ),
    ]
