# Generated by Django 5.1.4 on 2025-04-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_experience_level_user_hight_user_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hight',
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience_level',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
