# Generated by Django 5.1.4 on 2025-03-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_gallery_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
