# Generated by Django 5.1.4 on 2025-05-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_fcmtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('coach', 'Entrenador'), ('client', 'Cliente')], default='client', max_length=144),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Hombre'), ('FEMALE', 'Mujer')], default='MALE', max_length=144),
        ),
    ]
