# Generated by Django 5.1.4 on 2025-05-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_user_type_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Hombre'), ('female', 'Mujer')], default='male', max_length=144),
        ),
    ]
