# Generated by Django 5.1.4 on 2025-02-25 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=140, null=True)),
                ('video', models.CharField(blank=True, max_length=140, null=True)),
                ('sets', models.IntegerField(default=0)),
                ('repts', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.muscle')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
