# Generated by Django 5.1.4 on 2025-02-05 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='exercises/photos')),
                ('video', models.FileField(blank=True, default='default.jpg', null=True, upload_to='exercises/videos')),
                ('muscle', models.CharField(choices=[('CHEST', 'Pecho'), ('BACK', 'Espalda'), ('ARM', 'Brazo'), ('LEG', 'Pierna')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_catalog_set', to='equipments.equipment')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
