# Generated by Django 5.1.4 on 2025-04-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscle',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
