# Generated by Django 5.1.4 on 2025-02-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='repts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='photo',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
