# Generated by Django 5.1.4 on 2025-04-28 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_alter_catalog_options'),
        ('exercises', '0002_exercise_secondary_muscle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_catalog_set', to='catalogs.catalog'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muscle_catalog_set', to='catalogs.catalog'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
