# Generated by Django 5.1.4 on 2025-02-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='photo',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
