# Generated by Django 5.1.4 on 2025-04-22 06:44

import workouts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexcercise',
            name='data',
            field=models.JSONField(blank=True, default=workouts.models.default_sets, null=True),
        ),
    ]
