# Generated by Django 5.1.4 on 2025-04-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutexcercise_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexcercise',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexcercise',
            name='repts',
            field=models.IntegerField(default=12, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexcercise',
            name='sets',
            field=models.IntegerField(default=4, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexcercise',
            name='weight',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
