# Generated by Django 5.1.4 on 2025-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_workoutexcercise_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexcercise',
            name='order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
