# Generated by Django 5.1.4 on 2025-04-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workoutexcercise_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexcercise',
            options={'ordering': ['order']},
        ),
    ]
