# Generated by Django 5.1.4 on 2025-04-28 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercise_equipment_alter_exercise_muscle_and_more'),
        ('workouts', '0006_alter_workoutexcercise_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutexcercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='workoutexcercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.workout'),
        ),
    ]
