# Generated by Django 5.1.4 on 2025-04-28 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_workout_user_alter_workoutexcercise_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexcercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
        ),
    ]
