# Generated by Django 5.1.4 on 2025-04-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_workoutexcercise_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='level',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('medium', 'Medio'), ('advanced', 'Avanzado')], default='beginner', max_length=140),
        ),
    ]
