# Generated by Django 5.1.4 on 2025-05-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
        ('workouts', '0009_workout_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='day',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='level',
        ),
        migrations.AddField(
            model_name='workout',
            name='routines',
            field=models.ManyToManyField(to='routines.routine'),
        ),
        migrations.DeleteModel(
            name='WorkoutExcercise',
        ),
    ]
