# Generated by Django 5.1.4 on 2025-05-17 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('workouts', '0010_remove_workout_exercises_rename_name_workout_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.client'),
        ),
    ]
