# Generated by Django 5.1.4 on 2025-05-17 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('workouts', '0011_workout_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.client'),
        ),
    ]
